name: release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - "v*"

permissions: {}

jobs:
  build:
    name: tag release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
    - name: Export RELEASE_TAG var
      run: echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV

    - name: checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Install go
      uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: '1.22'

    - name: Apply Orange patch
      run: |
        cp -ar patches/* .
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Generate release artifacts and notes
      run: |
        export REGISTRY=ghcr.io/${{ github.repository_owner }}
        export REGISTRY=$(echo $REGISTRY | tr '[A-Z]' '[a-z]')
        export VERSION=${{ env.RELEASE_TAG }}
        make release
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        prerelease: false
        files: |
            templates/infrastructure-components.yaml
            LICENSE
        body: |
          Release version ${{ env.RELEASE_TAG }}
